version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "kdudka"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "lzaoral"
