language: c
compiler: gcc

install:
    - sudo apt-get install cmake valgrind

script:
    - make distcheck

matrix:
    include:
        - name: "Ubuntu LTS 2014 (trusty)"
          dist: trusty

        - name: "Ubuntu LTS 2016 (xenial)"
          dist: xenial

        - name: "Ubuntu LTS 2018 (bionic)"
          dist: bionic

        - name: "Ubuntu LTS 2020 (focal)"
          dist: focal
          # work around broken Ubuntu repos (libc6-dbg does not match libc6 version)
          install:
            - sudo apt-get install cmake
