#!/bin/bash

# Copyright (C) 2012-2013 Red Hat, Inc.
#
# This file is part of cppcheck-gcc.
#
# cppcheck-gcc is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# cppcheck-gcc is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cppcheck-gcc.  If not, see <http://www.gnu.org/licenses/>.

SELF="$0"
TOOL="`basename "$SELF"`"

# FIXME: this is not going to work well when cross-compiling
ARCH_DEF="-D__`uname -i`__"

# pretend GCC
ARCH_DEF="$ARCH_DEF -D__GNUC__"

# assume x86_64
ARCH_DEF="$ARCH_DEF -D__WORDSIZE=64"

CPPCHECK_TEMPLATE="'{file}:{line}: {severity}: {id}: {message}'"
CPPCHECK_DEF_ARGS="--template=$CPPCHECK_TEMPLATE --inline-suppr"
CPPCHECK_DEF_ARGS="$CPPCHECK_DEF_ARGS $ARCH_DEF --quiet"

CPPCHECK_SUPPLIST="/usr/share/cppcheck-gcc/default.supp"
if test -r "$CPPCHECK_SUPPLIST"; then
    CPPCHECK_DEF_ARGS="$CPPCHECK_DEF_ARGS --suppressions-list=$CPPCHECK_SUPPLIST"
fi

test -n "$CPPCHECK"      || CPPCHECK="cppcheck"
test -n "$CPPCHECK_ARGS" || CPPCHECK_ARGS="$CPPCHECK_DEF_ARGS"

match() {
    grep "$@" > /dev/null
}

pick_defs_and_incs() {
    while [ 0 -lt $# ]; do
        if printf "%s\n" "$1" | match '^-include$'; then
            # gcc -include
            printf " '--include=%s'" "$2"
            shift; shift
            continue
        fi

        if printf "%s\n" "$1" | match -E '^-i(quote|system)$'; then
            # gcc -iquote/-isystem
            printf " '-I%s'" "$2"
            shift; shift
            continue
        fi

        printf " '%s'\n" "$1" | grep -E "^ '(-D|-I)" | tr -d '\n'
        shift
    done
}

pick_source_files() {
    for i in "$@"; do
        printf " %s\n" "$i" | grep -E '\.(c|C|cc|cpp|cxx)$' | tr -d '\n'
    done
}

debug_cmd() {
    printf "+"
    for i in "$@"; do
        printf " '%s'" "$i"
    done
    printf "\n"
}

run_cmd() {
    if test -n "$CPPCHECK_DEBUG_FD" && test -w "/dev/fd/$CPPCHECK_DEBUG_FD"; then
        debug_cmd "$@" >&"$CPPCHECK_DEBUG_FD"
    fi

    "$@"
}

run_cppcheck() {
    C_FILES="`pick_source_files "$@"`"
    test -n "$C_FILES" || return 1

    for i in "$@"; do
        if printf "%s\n" "$i" | match '^-E'; then
            # skip cppcheck when only preprocessing files, it would break ccache
            return 0
        fi
    done

    if printf "%s\n" "$C_FILES" | match -F 'conftest.c'; then
        # avoid unnecessary delays when running autoconf checks
        return 0
    fi

    if printf "%s\n" "$C_FILES" | match -F '../test.c'; then
        # avoid unnecessary delays when running waf checks
        return 0
    fi

    if printf "%s\n" "$C_FILES" | match 'CMakeFiles/CMakeTmp/testCXXCompiler.cxx'
    then
        # avoid a panic of CMake when checking basic functionality of CXX
        return 0
    fi

    eval run_cmd "$CPPCHECK" `pick_defs_and_incs "$@"` ${CPPCHECK_ARGS} $C_FILES
}

remove_self_from_path() {
    PATH="`printf "%s\n" "$PATH" | while read -d: dir
    do
        real_name="$(basename "$(readlink -f "$dir/$TOOL")")"
        if test "$real_name" = "cppcheck-gcc"; then
            # remove path to itself in order to prevent an infinite loop
            continue
        fi

        printf ":%s" "$dir"
    done`"
    export PATH
}

remove_self_from_path
run_cmd "$TOOL" "$@"
EC=$?

run_cppcheck "$@"
exit $EC
