#!/bin/bash

# Copyright (C) 2012-2013 Red Hat, Inc.
#
# This file is part of cppcheck-gcc.
#
# cppcheck-gcc is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# cppcheck-gcc is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cppcheck-gcc.  If not, see <http://www.gnu.org/licenses/>.

# FIXME: this is not going to work well when cross-compiling
ARCH_DEF="-D__`uname -i`__"

CPPCHECK_TEMPLATE="'{file}:{line}: {severity}: {id}: {message}'"
CPPCHECK_DEF_ARGS="--template=$CPPCHECK_TEMPLATE --inline-suppr"
CPPCHECK_DEF_ARGS="$CPPCHECK_DEF_ARGS -I/usr/include $ARCH_DEF"

CPPCHECK_SUPPLIST="/usr/share/cppcheck-gcc/default.supp"
if test -r "$CPPCHECK_SUPPLIST"; then
    CPPCHECK_DEF_ARGS="$CPPCHECK_DEF_ARGS --suppressions-list=$CPPCHECK_SUPPLIST"
fi

test -n "$CPPCHECK"      || CPPCHECK="cppcheck"
test -n "$CPPCHECK_ARGS" || CPPCHECK_ARGS="$CPPCHECK_DEF_ARGS"

match() {
    grep "$@" > /dev/null
}

pick_defs_and_incs() {
    while [ 0 -lt $# ]; do
        if printf "%s\n" "$1" | match '^-include$'; then
            printf " '--include=%s'" "$2"
            shift; shift
            continue
        fi

        printf " '%s'\n" "$1" | grep -E "^ '(-D|-I)" | tr -d '\n'
        shift
    done
}

pick_source_files() {
    for i in "$@"; do
        printf " %s\n" "$i" | grep -E '\.(c|C|cc|cpp|cxx)$' | tr -d '\n'
    done
}

run_cmd() {
    if test -w /dev/fd/3; then
        printf "+" >&3
        for i in "$@"; do
            printf " '%s'" "$i" >&3
        done
        printf "\n" >&3
    fi

    "$@"
}

run_cppcheck() {
    C_FILES="`pick_source_files "$@"`"
    test -n "$C_FILES" || return 1

    if printf "%s\n" "$C_FILES" | match 'conftest.c'; then
        # avoid unnecessary delays when running autoconf checks
        return 0
    fi

    if printf "%s\n" "$C_FILES" | match 'CMakeFiles/CMakeTmp/testCXXCompiler.cxx'
    then
        # avoid a panic of CMake when checking basic functionality of CXX
        return 0
    fi

    eval run_cmd "$CPPCHECK" `pick_defs_and_incs "$@"` ${CPPCHECK_ARGS} $C_FILES
}

CC="/usr/bin/`basename "$0"`"
run_cmd "$CC" "$@"
EC=$?

run_cppcheck "$@"
exit $EC
