cscppc(1)
=========
:doctype: manpage

NAME
----
cscppc - a compiler wrapper that runs cppcheck in background


SYNOPSIS
--------
*cscppc* ['--help' | '--print-path-to-wrap']


DESCRIPTION
-----------
cscppc is a compiler wrapper that runs cppcheck in background.  Create a
symbolic link to cscppc named as your compiler (gcc, g++, ...) and put it
to your $PATH.

The following parameters are given to cppcheck by default:

    * -D\__GNUC__

    * -D\__STDC__

    * -D\__i386__ {nbsp}{nbsp}{nbsp}{nbsp}{nbsp}    [32bit architecture only]

    * -D__WORDSIZE=32{nbsp}                         [32bit architecture only]

    * -D\__x86_64__ {nbsp}{nbsp}{nbsp}              [64bit architecture only]

    * -D__WORDSIZE=64{nbsp}                         [64bit architecture only]

    * --inline-suppr

    * --quiet

    * --template="\{file}:\{line}: \{severity}: \{id}: \{message}"

    * --suppressions-list=/usr/share/cscppc/default.supp

The following parameters are passed to cppcheck from compiler's command line:

    * -D...

    * -I...

The following file extensions are recognized as C/C++ source files:

    * c

    * C

    * cc

    * cpp

    * cxx

If cscppc is installed on system, the following command activates the wrapper:
-------------------------------------------------
export PATH="`cscppc --print-path-to-wrap`:$PATH"
-------------------------------------------------


OPTIONS
-------
*--help*::
    Prints basic usage information.

*--print-path-to-wrap*::
    Prints path to the directory with symlinks to the cscppc executable.


EXIT STATUS
-----------
cscppc propagates the exit status returned by the compiler (in case cscppc
succeeds to run the compiler).  The exit status returned by cppcheck does not
affect the resulting exit status.


ENVIRONMENT VARIABLES
---------------------
*DEBUG_CSCPPC*::
    If set to a non-empty string, cscppc outputs the list of parameters given
    to cppcheck to the standard output.

*CSCPPC_ADD_OPTS*::
    cscppc expects a colon-separated list of Cppcheck options that should be
    appended to command line prior to invoking Cppcheck.  The options are
    appended even if they already appear in the command line and they are
    always appended at the end of the command line.


BUGS
----
Please report bugs and feature requests at https://github.com/kdudka/cscppc .


AUTHOR
------
Written by Kamil Dudka.


COPYING
-------
Copyright \(C) 2013-2014 Red Hat, Inc. Free use of this software is granted
under the terms of the GNU General Public License (GPL).  See the COPYING file
for details.
