---
name: Ubuntu CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu:
    name: Ubuntu ${{ matrix.version }} (${{ matrix.compiler }}${{ matrix.version == 22.04 && ' with sanitizers' || '' }})
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang, gcc]
        version: [22.04]

    runs-on: ubuntu-${{ matrix.version }}
    env:
      CC: ${{ matrix.compiler }}
      CFLAGS: -Werror

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependecies
        run: |
          sudo apt update
          sudo apt install -y asciidoc-base

      - name: '[clang] Install a default version for Ubuntu ${{ matrix.version }}'
        if: matrix.compiler == 'clang'
        run: sudo apt install -y clang

      - name: Build and check
        run: |
          if [[ "${{ matrix.version }}" == 22.04 ]]; then
            make distcheck-sanitizers
          else
            make distcheck
          fi
