---
name: Coverity

on:
  push:
    branches: [main]

jobs:
  coverity:
    if: github.repository == 'csutils/cscppc'
    name: Coverity Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Coverity scan
        uses: vapier/coverity-scan-action@v1
        with:
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          project: csutils/cscppc
          command: make
